### ISSUE TITLE
Fake project

### ISSUE THREAD

**Issue by sleeping3119** [behnamnasehi/playsho-nest#1]
nothing working it is just hello world page

**Comment by binaryb3ast** [comment]
this project provide api for https://github.com/binaryb3ast/playsho that its an app for watching movie with ur friends

**Comment by sleeping3119** [comment]
why localhost:3000 is saying hello world
where is the api?

**Comment by binaryb3ast** [comment]
in other controllers 
like src/user/user.api.controller.ts 
src/room/room.api.controller.ts

**Comment by sleeping3119** [comment]
please correct me if i am wrong

./dist/device/device.api.controller.d.ts ./dist/device/device.api.controller.js ./dist/device/device.api.controller.js.map ./dist/room/room.api.controller.d.ts

**Comment by sleeping3119** [comment]
Can you tell me all api's path as i dont know Javascript and where to use them in Android studio in android app project there might be any single file where i should provide the all apis.

Also correct me if i am wrong
if this is the api:
./dist/device/device.api.controller.d.ts 

Then 
```
http://ip:3000/dist/device/device.api.controller.d.ts
``` 
is the local url of api and i can set them in Android app source code to work in local network
